### ISSUE TITLE
Unknown Error retrieving susbcriptions from Azure Account extension

### ISSUE THREAD

**Issue by jingkenyan** [microsoft/vscode-tools-for-ai#1585] opened 2022-06-01 19:07 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSessionsChanged
Error type: 123
Error Message: Unknown Error retrieving susbcriptions from Azure Account extension

Version: 0.10.0
OS: linux
OS Release: 5.4.0-1068-azure
Product: Visual Studio Code
Product Version: 1.67.2
Language: en

<details>
<summary>Call Stack</summary>

```
_.<anonymous> extension.js:2:2324475
s extension.js:2:2321343
```

</details>

**Comment by sevillal** [comment] 2022-06-03 18:32
@tbombach this seems to be a duplicate of the onSessionsChanged issue, could you please take a look?

**Comment by shsuman** [comment] 2022-09-22 08:33
@jingkenyan We have shipped a fix for this issue. Can you please upgrade the extension to 0.18.0 and let us know if its fixed for you?

**Comment by shsuman** [comment] 2022-09-30 09:46
Closing this because of inactivity. Please reopen if need be :)

**Closed by shsuman** 2022-09-30 09:46 UTC
Labels: customer-issue
