### ISSUE TITLE
[Triage] Can no longer run Jupyter for Azure ML

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-tools-for-ai#1229] opened 2021-08-17 13:33 UTC
Initially created at https://github.com/microsoft/vscode/issues/128750 by @MathieuBeaudoin

---

1) Open an .ipynb file from Azure ML Notebooks using "Edit in VS Code (preview)"
2) VS Code tells me it can't open the file, that I need a jupyter-notebook extension (it used to work though)
3) I go to Extensions, type "jupyter" in the search bar, chose "ms-toolsai.jupyter" from Microsoft and click on "Install in Azure ML".
4) I get the following error message: '[UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character'

I have not changed anything in my VS Code or Azure ML settings since it last worked. One day it worked, the next it suddenly didn't.

**Comment by SiddhanthUnnithan** [comment] 2021-08-19 17:11
Hi @MathieuBeaudoin, can you confirm whether you're still seeing this issue? One other option is to initiate the connection, reload the window, and then try opening the notebook. We've been seeing an intermittent issue with the first connection initiated that has been fixed by reloading the window. The issue is related to dependent extensions not loading / activating correctly.

**Comment by MathieuBeaudoin** [comment] 2021-08-19 17:51
> Hi @MathieuBeaudoin, can you confirm whether you're still seeing this issue? One other option is to initiate the connection, reload the window, and then try opening the notebook. We've been seeing an intermittent issue with the first connection initiated that has been fixed by reloading the window. The issue is related to dependent extensions not loading / activating correctly.

I am not very familiar with VS Code and a search for "connection" in the documentation yields zero results. When you suggest that I "initiate the connection", do you mean from VS Code itself? If so, how do I do that exactly? I found that by using "File>Close Remote Connection" I can then click on an Azure icon on the left-side bar, which lets me see things like Compute Instances, Datasets, Environments, etc... but not Notebooks (which is what I actually care about). I then see options to create jobs and whatnot, but nothing about Connection or Authentication.

Then you mention "reloading the window", is there a specific option to do that, or are you talking about closing the window, then opening a new one?

**Comment by MathieuBeaudoin** [comment] 2021-08-19 18:07
I figured out to connect from VS Code. The process was a bit convoluted but I can now access my Azure-based Notebooks through VS Code.

**Comment by SiddhanthUnnithan** [comment] 2021-08-24 18:20
Sorry for the delayed response here @MathieuBeaudoin. "Initiate connection" was referring to starting the connection from either VS Code or the Azure ML Studio. With the latter, you can click one of "Edit in VS Code" or "VS Code" links from the Notebooks and Compute Instance pages, respectively:

[Compute Instance Page]
![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/bacb67aa-9a20-4988-ae9a-8996bfdc97a6)

[Notebook Page]
![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/618f60a7-a66f-4050-ae38-02e189a83737)

I think we can do a better job of explaining how VS Code and your Azure ML Notebooks work together. In the Studio, you can go to the "Notebooks" tab to view files and then run them against a compute instance. Because VS Code includes more functionality than just file viewing and running (e.g., Git, debugger, terminal), the entire VS Code window must be connected to a remote compute (i.e., compute instance) and then from there you can access your Notebooks.

It might be worthwhile for us to investigate including a Notebooks tab in the extension tree view with an entry point to your compute instances. Once you have a compute instance selected, you can view your Notebook (and other) files on the left-hand side:

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/880a3e6d-ae88-4e79-8ad8-278bce70e6ee)

"Reloading" the window is an operation in VS Code wherein your current window is opened and closed, and all extensions are re-activated. Any file that you had open previously, regardless of whether they've been saved, will get reloaded with all the state persisted. You can reload your window through by invoking "Ctrl + Shift + P" and searching for "Reload Window" (on Windows).

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/994094f9-1554-4f94-8bdb-d821f12d272e)

Let me know if you have any other questions! I'm glad your issue was resolved.

**Closed** 2022-03-25 16:51 UTC
Labels: accessibility
