### ISSUE TITLE
Connect to compute instance failed with unknown 400 error

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#1477] opened 2022-03-04 08:28 UTC
## Expected Behavior
Able to connect to remote Compute Instance

## Actual Behavior
Compute Instance connection fails with a 400 error

## Specifications

  - VS Code Version:
  - Platform:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/779479/156727217-0b2f0bfe-1365-4ee6-8d9d-e2489d8d2f4e.png)

**Comment by j0rd1smit** [comment] 2022-03-04 18:17
I'm also have similiar problems connect to AzureML compute instance. I haven't been able to access it all day
![image](https://user-images.githubusercontent.com/22663455/156819403-749f5041-7c4a-4825-a848-4e6c4b2d9098.png)

**Comment by MichaMucha** [comment] 2022-03-04 18:34
Same, it worked on 1.64 and stopped working after the update to 1.65

**Comment by joolz** [comment] 2022-03-07 08:30
Same here since last week.

**Comment by mrussoCGNZ** [comment] 2022-03-07 09:57
Same issue after updating to 1.65

Version: 1.65.0 (user setup)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:12:08.962Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by sevillal** [comment] 2022-03-07 20:54
@j0rd1smit @joolz @MichaMucha @mrussoCGNZ we have fixed the remote connection issue on version 0.8.0 of Azure Machine Learning - Remote extension. Please try upgrading and reconnection, note that is should work both in VS Code 1.64 and 1.65.

**Comment by MichaMucha** [comment] 2022-03-08 00:27
Thanks! Confirmed it works now on 1.65

**Comment by joolz** [comment] 2022-03-08 07:24
Confirmed, Works again on vsc 1.65.0. Thanks!

**Comment by marcusRB** [comment] 2022-03-08 08:29
Confirmed, it works on vsc 1.65.0 Thanks @sevillal

**Comment by shsuman** [comment] 2022-04-04 10:30
Closing as this has been fixed in 0.8.0 release

**Closed by shsuman** 2022-04-04 10:30 UTC
Labels: amlext-remote, needs triage
