### ISSUE TITLE
Test for Visual code AI simple

### ISSUE THREAD

**Issue by lisztjr** [microsoft/vscode-tools-for-ai#1497] opened 2022-03-12 04:22 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSubscriptionsChanged
Error type: r
Error Message: {
    "name": "UserCancelledError"
}

Version: 0.6.28
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.65.0
Language: pt-br

<details>
<summary>Call Stack</summary>

```
extension.js:2:4673269extension.js:2:4673269
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by tbombach** [comment] 2022-03-22 00:18
Hi @lisztjr, thank you for reporting this! We have a fix for this issue in our next release, which we expect to make public next week.

Duplicate of https://github.com/microsoft/vscode-tools-for-ai/issues/1458

**Closed by tbombach** 2022-03-22 00:18 UTC
Labels: needs triage
