### ISSUE TITLE
When a local run never fails, the spinning icon never ever goes away.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#305] opened 2019-09-26 00:21 UTC
Even after stopping and starting. I ran a python script that had no calls to azure. It may have just stopped running due to not having a package.

**Comment by tbombach** [comment] 2019-09-30 19:06
Assigning this to myself

**Comment by shsuman** [comment] 2019-10-07 13:10
The icon is directly dependent on the state of any run. If the icon is spinning forever, that means the state of the experiment never changes from Starting to Running, probably not because the experiment is not run but the azureml-script which is used to run the python script does not have the required packages installed in the system so that it can be executed successfully. 

There is an option in the run config of setting userManagedDependencies to false. This may be a solution to the user not having all the packages in their system

**Comment by tbombach** [comment] 2019-10-11 17:31
A few findings:
- I tried a bunch of local runs and found that errors at almost any stage can leave the experiment in a "Starting" state. The local run path needs some logging so that we can tell where failures come from, so I'll send out a PR for that.
- The local run in docker path can easily lead users to a bad path. We need more documentation for this option, since they need to install docker, make sure it's running and pull the container image for running azureml. Might not be the most important thing (since we usually send the user down the path of running via local python instance), but I'll log an issue for it.

### Root cause
I ran an experiment, following the golden path and using the train script from the getting started documents. I selected the local compute but the experiment never switched from "Starting" to Queued or Completed. I used the `az ml` CLI to run the experiment outside of the AML extension with the same runconfig generated. It ran successfully and the run switched to "Completed". From debugging the extension, we successfully submitted the experiment to AML service but we never actually successfully run the project we download from the AML response. **I looked at the `Invocation.sh` script that we use to run the project locally, it has read/write permission but not execution permission.**. This happens for both docker and user machine local runs. After I ran chmod, I could execute the invocation script successfully. When I unzipped the downloaded project myself, the Invocation script does have execution permission, so it seems like the issue is in the unzip library (adm-zip). **The package API doesn't include any options for permissions, so I'm investigating other packages to replace it.**

**Comment by tbombach** [comment] 2019-10-11 19:06
Found a replacement npm package (https://www.npmjs.com/package/extract-zip) that allows us to specify file mode during zip extraction. Tested successfully on mac - will verify on windows next.

**Comment by davidateek** [comment] 2019-10-23 15:43
@tbombach could you share your solution with me - running into the same issue

**Closed** 2019-11-12 21:53 UTC
