### ISSUE TITLE
Unable to export PDF / HTML

### ISSUE THREAD

**Issue by KenMsft** [microsoft/vscode-tools-for-ai#820] opened 2020-11-20 00:05 UTC
## Expected Behavior

Export / PDF should succeed

## Actual Behavior
[I 00:04:48.695 NotebookApp] Kernel shutdown: ea8e4742-b502-4d78-86aa-33a4a6f2671d
[I 00:04:49.799 NotebookApp] Creating new notebook in /Users/kenwong/forecasting-beer-remote
[I 00:04:50.003 NotebookApp] Saving Untitled.ipynb
[I 00:04:50.401 NotebookApp] Kernel shutdown: cdc0a53b-fadd-4558-aee3-0bf285fa191f
[W 00:04:51.411 NotebookApp] Got events for closed stream None
[W 00:04:51.412 NotebookApp] Got events for closed stream None
[I 00:04:51.689 NotebookApp] Kernel started: c91acd98-9862-442e-815f-24eac7f43445, name: conda-env-azureml_py36-py
[W 00:04:51.696 NotebookApp] delete /Users/kenwong/forecasting-beer-remote/t-ddadc9e8-6da3-45ce-a597-0e9869ac3cf1.ipynb
[W 00:04:51.696 NotebookApp] Skipping trash for /home/azureuser/cloudfiles/code/Users/kenwong/forecasting-beer-remote/t-ddadc9e8-6da3-45ce-a597-0e9869ac3cf1.ipynb, on different device to home directory
> /anaconda/envs/azureml_py36/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py jupyter nbconvert /tmp/37517739-5085-49b0-8f03-91b747edd8fc/test434.ipynb --to html --output tmp-27346FT9yJ7DDcL2U.html --output-dir /tmp --debug
Error 2020-11-20 00:05:00: Export failed [Error: [NbConvertApp] Searching ['/mnt/batch/tasks/shared/LS_root/mounts/clusters/computedemo1/code', '/home/azureuser/.jupyter', '/anaconda/envs/azureml_py36/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[NbConvertApp] Looking for jupyter_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /anaconda/envs/azureml_py36/etc/jupyter
[NbConvertApp] Loaded config file: /anaconda/envs/azureml_py36/etc/jupyter/jupyter_config.json
[NbConvertApp] Looking for jupyter_config in /home/azureuser/.jupyter
[NbConvertApp] Looking for jupyter_config in /mnt/batch/tasks/shared/LS_root/mounts/clusters/computedemo1/code
[NbConvertApp] WARNING | Config option `kernel_spec_manager_class` not recognized by `NbConvertApp`.
[NbConvertApp] Looking for jupyter_nbconvert_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /anaconda/envs/azureml_py36/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /home/azureuser/.jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /mnt/batch/tasks/shared/LS_root/mounts/clusters/computedemo1/code
[NbConvertApp] Converting notebook /tmp/37517739-5085-49b0-8f03-91b747edd8fc/test434.ipynb to html
[NbConvertApp] Notebook name is 'tmp-27346FT9yJ7DDcL2U'
[NbConvertApp] Template paths:
	/home/azureuser/.local/share/jupyter/nbconvert/templates/html
	/anaconda/envs/azureml_py36/share/jupyter/nbconvert/templates/html
	/usr/local/share/jupyter/nbconvert/templates/html
	/usr/share/jupyter/nbconvert/templates/html
	/anaconda/envs/azureml_py36/share/jupyter/nbconvert/templates/lab
	/anaconda/envs/azureml_py36/share/jupyter/nbconvert/templates/base
	/home/azureuser/.local/share/jupyter
	/home/azureuser/.local/share/jupyter/nbconvert/templates
	/home/azureuser/.local/share/jupyter/nbconvert/templates/compatibility
	/anaconda/envs/azureml_py36/share/jupyter
	/anaconda/envs/azureml_py36/share/jupyter/nbconvert/templates
	/anaconda/envs/azureml_py36/share/jupyter/nbconvert/templates/compatibility
	/usr/local/share/jupyter
	/usr/local/share/jupyter/nbconvert/templates
	/usr/local/share/jupyter/nbconvert/templates/compatibility
	/usr/share/jupyter
	/usr/share/jupyter/nbconvert/templates
	/usr/share/jupyter/nbconvert/templates/compatibility
[NbConvertApp] Applying preprocessor: TagRemovePreprocessor
[NbConvertApp] Applying preprocessor: RegexRemovePreprocessor
[NbConvertApp] Applying preprocessor: coalesce_streams
[NbConvertApp] Applying preprocessor: HighlightMagicsPreprocessor
[NbConvertApp] Applying preprocessor: CSSHTMLHeaderPreprocessor
[NbConvertApp] Attempting to load template index.html.j2
[NbConvertApp]     template_paths: /home/azureuser/.local/share/jupyter/nbconvert/templates/html:/anaconda/envs/azureml_py36/share/jupyter/nbconvert/templates/html:/usr/local/share/jupyter/nbconvert/templates/html:/usr/share/jupyter/nbconvert/templates/html:/anaconda/envs/azureml_py36/share/jupyter/nbconvert/templates/lab:/anaconda/envs/azureml_py36/share/jupyter/nbconvert/templates/base:/home/azureuser/.local/share/jupyter:/home/azureuser/.local/share/jupyter/nbconvert/templates:/home/azureuser/.local/share/jupyter/nbconvert/templates/compatibility:/anaconda/envs/azureml_py36/share/jupyter:/anaconda/envs/azureml_py36/share/jupyter/nbconvert/templates:/anaconda/envs/azureml_py36/share/jupyter/nbconvert/templates/compatibility:/usr/local/share/jupyter:/usr/local/share/jupyter/nbconvert/templates:/usr/local/share/jupyter/nbconvert/templates/compatibility:/usr/share/jupyter:/usr/share/jupyter/nbconvert/templates:/usr/share/jupyter/nbconvert/templates/compatibility
[NbConvertApp] Writing 568324 bytes to /tmp/tmp-27346FT9yJ7DDcL2U.html

	at a.executeCommand (/home/azureuser/.vscode-server/extensions/ms-toolsai.jupyter-2020.11.358541065/out/client/extension.js:1:443004)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)]

## Steps to Reproduce the Problem

  1.Create a simple notebook
  1.Export as HTML 
  

## Specifications

  - Version: 0.6.17 , VScode 1.51.1
  - Platform: Windows

**Comment by SiddhanthUnnithan** [comment] 2020-11-20 16:17
Tried reproducing this issue with the "Azure ML - Python 3.6" Kernel.

Export to Python script worked as expected.

Export to PDF failed because I didn't have TeX installed. This is expected behaviour.

Export to HTML worked **after** I changed the export path. The extension defaults to /<filename>.html. I changed the path to $CWD/<filename>.html.

Following up with Don & co. about the default export path.

**Comment by SiddhanthUnnithan** [comment] 2020-11-20 17:57
Followed up with Don and Claudia - suggested changing the default export path to either workspace root or parent directory of the Notebook being exported.

Issue here: https://github.com/microsoft/vscode-jupyter/issues/3991

@kenmsft can you follow up to see if changing the export directory fixes your export issue for  HTML files.

**Comment by SiddhanthUnnithan** [comment] 2021-01-11 18:47
Issue linked above was fixed so closing this issue.

**Closed** 2021-01-11 18:46 UTC
Labels: amlext-remote
