### ISSUE TITLE
AVKVY3WBG

### ISSUE THREAD

**Issue by dewedeth** [microsoft/vscode-tools-for-ai#1594] opened 2022-06-10 09:36 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSessionsChanged
Error type: 123
Error Message: Unknown Error retrieving susbcriptions from Azure Account extension

Version: 0.12.0
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.68.0
Language: en

<details>
<summary>Call Stack</summary>

```
_.<anonymous> extension.js:2:2329781
s extension.js:2:2326649
```

</details>

**Comment by shsuman** [comment] 2022-06-10 11:06
Duplicate of #1592

**Closed by shsuman** 2022-06-10 11:06 UTC
Labels: customer issue

**Comment by dewedeth** [comment] 2022-06-10 15:29
Dewed collection.Guided by CUDA ML,GIMP19 & Adobe PS/AI/CCS 3D layer mesh & curve kited Babel.Dev-Microsoft-tools, gcloud-cli-contributor,kali-Linux.Ubuntu.
