### ISSUE TITLE
Failed to connect to the remote extension host server (Error: Unknown Error occured)

### ISSUE THREAD

**Issue by pierrelouisbescond** [microsoft/vscode-tools-for-ai#1564] opened 2022-05-03 16:27 UTC
## Expected Behavior

Proper connection to Azure ML Studio Compute instance.

## Actual Behavior

_Note: This error message is the same for different Data Scientists / Data Engineers working in the same team but with different laptops and Windows versions, extensions, which makes us think the switch from 1.65.2 to 1.66.2 is causing this issue._

When updating from 1.65.2 to 1.66.2, VS Code is no longer able to connect to instances in Azure Machine Learning Studio.

Error messages are as follows:

```
Failed to connect to the remote extension host server (Error: Unknown Error occurred)

request to https://***********.francecentral.instances.azureml.ms/api/terminals?****** failed, reason: certificate signature failure

[Extension Host] Unhandled Error: ENOPRO: No file system provider found for resource 'vscode-remote://amlext***/home/azureuser/***'    at p.withProvider (vscode-file://vscode-app/c:/Users/*******/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:27776)    at processTicksAndRejections (node:internal/process/task_queues:96:5)    at async p.exists (vscode-file://vscode-app/c:/Users/********/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:30371)    at async Promise.all (index 0)    at async vscode-file://vscode-app/c:/Users/********/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2110:2110
D @ console.ts:137
```

![vs_code_1 66 2_failure](https://user-images.githubusercontent.com/65066394/166405598-3353dadd-9cb3-4777-9ca1-33bed3b9e74d.png)

## Steps to Reproduce the Problem

  1. Switch from 1.65.2 to 1.66.2

## Specifications

- VS Code Version: 1.66.2
- OS Version: Windows_NT x64 10.0.18363

**Comment by tbombach** [comment] 2022-05-07 20:00
@pierrelouisbescond I'm sorry you're experiencing this issue. We'll investigate and get to the bottom of this. @sevillal could you look into this?

**Comment by sevillal** [comment] 2022-05-09 20:13
@pierrelouisbescond last week a new version of VS Code 1.67.0, could you please try with that version to see if that's still reproducible?

**Comment by pierrelouisbescond** [comment] 2022-05-10 04:55
@sevillal I made additional experiments yesterday and this morning:

* V1.67.0 installed on my professional Surface, at the office: connexion is working
* V1.67.0 installed on my professional Surface, from home: connexion fails
* V1.67.0 installed on my ***personal*** Surface, from home: connexion is working
* V1.65.2 installed on my professional Surface, at the office: connexion is working
* V1.65.2 installed on my professional Surface, from home: connexion is working

So there is a change happening between 1.65.2 and 1.67.0 that we cannot figure out. Should we open a ticket through our Azure support?

**Comment by sevillal** [comment] 2022-05-11 00:44
Thanks @pierrelouisbescond for the detailed results of your experimentation. 

I noticed that the error is SSL related and it is thrown when trying to access the Jupyter terminals API in an specific environment (your professional surface from home):

1. Are you trying to connect to the same compute instance on your experiment 2 and 5?
2. For experiment 2, what happen after retrying the connection? is the same error thrown?
3. In your experiment 2, could you please try visiting the ML Studio and opening a terminal on that CI?
![image](https://user-images.githubusercontent.com/56176070/167746852-3c5cfb3a-370e-456b-b221-3fa6f2652d92.png)

**Comment by pierrelouisbescond** [comment] 2022-05-11 04:03
@sevillal 
Are you trying to connect to the same compute instance on your experiment 2 and 5?
**Yes and I made sure only one of my compute instances is running to avoid any mistake.**

For experiment 2, what happen after retrying the connection? is the same error thrown?
**I have retested 1.67.0 this morning and got the same error message a couple of times. However, I have noticed a small change: with 1.66.2, the first error message was mentioning "Unkown error occurred" whereas with 1.67.0, it is now referring to the certificate signature failure:"**

![image](https://user-images.githubusercontent.com/65066394/167766314-4fcd8e45-360b-4695-827b-e922a8efbee2.png)

In your experiment 2, could you please try visiting the ML Studio and opening a terminal on that CI? 
**Yes, it works fine**
![image](https://user-images.githubusercontent.com/65066394/167766065-63ffa23e-8eda-416a-9eb7-6db1f53dbebf.png)

If at some point you feel it would be better to make some live tests, I can free myself as this bug concerns our whole Data Science team (6 Data Scientists, 3 Data Engineers, 1 Machine Learning Engineer 🤔)

Pierre-Louis

**Comment by sevillal** [comment] 2022-05-11 15:22
@pierrelouisbescond thanks for sharing that information. Let's setup a call, what's your availability for the next days?

**Comment by sevillal** [comment] 2022-05-11 16:06
@pierrelouisbescond you can email me your availability at sevillal@microsoft.com.

**Comment by sevillal** [comment] 2022-05-13 16:44
Pierre and I had a triage call, here the findings during the call:
- VS Code 1.65.2, Azure ML Main v.10, Azure ML remote v.12 => Connection successful.
- VS Code 1.67 or 1.67.1, Azure ML Main v.10, Azure ML remote v.12 => Failed to connect with certificates error (nothing else found in the logs)

Follow ups:
- Analyze the "openssl" logs grabbed during the call
- How can the VS Code version affect the communication with the Jupyter APIs that the extension is making?

**Comment by sevillal** [comment] 2022-06-03 22:30
- openssl logs look ok
- Next: Since calling the Jupyter Terminal REST API is failing, we are trying calling the API from inside VSCode though a simple REST client to see if this reproduces.

**Comment by sevillal** [comment] 2022-06-06 18:17
6/6/22 triage call
- REST calls to Jupyter Terminal API from a VS Code REST client extension works fine
- Remote connection works in 1.65.2 VS Code stable
- Remote connection fails in latest VS Code insiders (with cert issue)
- "Azure ML: Connect to CI Jupyter Server" fails with same error
- Given that an older version of VS Code + the same extensions version works, this seems to be an issue with either the environment or the network itself.

Next:
- Pierre will ask their network team to trace calls to Jupyter terminals API. We are hoping to see calls from older version of VS Code success and the new ones fail, then comparing could give us a pointer.
- Pierre will try to repro with a fresh environment
- Azure ML team: Investigate with VS Code core if there could be a change in core affecting this

**Comment by sevillal** [comment] 2022-07-01 14:35
Closing this since customer reported this has been fixed with a network change on their side by allowing azure ml subdomain in their firewall.

**Closed by sevillal** 2022-07-01 14:35 UTC
Labels: customer issue
