### ISSUE TITLE
[Verify] "Azure ML Extension loading" looping when connected to remote VM via SSH

### ISSUE THREAD

**Issue by sjuratov** [microsoft/vscode-tools-for-ai#871] opened 2021-01-05 16:00 UTC
## Expected Behavior
When I SSH to remote VM (AML CI), I can use AML extension.

## Actual Behavior
After I SSH to remote Azure VM (AML CI), I navigate to "Azure" extension in left hand rail. This immediately kicks of "Azure ML Extension loading" msg in bottom right corner of VS Code. Shortly after I get a prompt to install Azure Account and Python extensions, when both are already installed on remote (SSH) VM. AML extension is also installed on remote (SSH) VM but for some reason grayed out. Even if I say that I want Azure Account and Python extensions to be installed, and that happens without a problems, "Azure ML Extension loading" msg keeps on looping and extension never loads. Disconnecting from SSH session and reconnecting doesn't help - I end up at exactly same starting point.

NOTE: This used to work until some time end of 2020.

## Steps to Reproduce the Problem

See actual behavior.

## Specifications

  - Version: AML extension v0.6.19
  - Platform: VS Code is running on Win10 Enterprise, remote VM is Ubuntu (AML CI)

**Comment by SiddhanthUnnithan** [comment] 2021-01-11 18:20
Hey @sjuratov - thanks for bringing this to our attention. For starters, sorry that you're running into this regression. This is a known issue that came up after we shipped the new "remote" feature.

The reason why this is occurring is because we had to temporarily change the install pattern of the AML extension - the Python and Az Account extensions were removed as hard dependencies.

We observed that the extension was resolving dependencies correctly both in the "local" window and when creating a new "remote" instance. However we also noticed that the extension was registered as remote and that our install-prompt logic for Python and Az Account wasn't working in the remote window (this includes our own, Remote-WSL, Remote-SSH).

Our top-most priority for December was to fix the dependency issues and get the extension working in remote instances. We've made the necessary changes (i.e. creating a second extension specifically to manage remote) and have validated that this fixes the dependencies and the issue you're seeing. There's still some further testing/validation we need to do before we ship this month.

Let me know if you have any additional questions!

**Comment by SiddhanthUnnithan** [comment] 2021-01-11 22:10
We need to validate that the second remote extension fixes this issue for other remote windows (Remote-*).

CC @shsuman when testing the second remote extension (post-publish).

**Comment by sjuratov** [comment] 2021-01-13 11:45
Thanks @SiddhanthUnnithan ! It's good to hear that solution is already in flight and should be released this month.

**Comment by tbombach** [comment] 2021-02-01 18:33
I went through these steps and did not see the loading loop behavior with the second remote extension. This should be fixed with our next release.

**Closed** 2022-03-25 16:39 UTC
Labels: shipblocker, amlext-remote
