### ISSUE TITLE
Validate compute instance can be used by the user before opening remote connection

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1043] opened 2021-05-21 16:24 UTC
We should validate that the current user can use the compute instance he wants to remotely connect before trying to open the connection.

Error seen:
- Studio enables VSCode link in CI not assigned to the user
- User clicks VSCode, but connection fails since not assigned to him

**Comment by SiddhanthUnnithan** [comment] 2021-05-24 17:57
Keeping in Upstream to track whether AML will make the change any time soon. If not, we may need to prioritize this work to avoid users running into "get_terminal_session" issue (hypothesis).

**Comment by SiddhanthUnnithan** [comment] 2021-08-04 17:39
I'm not able to reproduce this issue so I'm assuming AML made the fix to only allow users assigned to the compute instance to click on the VS Code option. Closing for now but will reopen if we're still seeing this issue.

I don't think we need to add logic on our side to check if the compute instance is assigned to the signed in user as an unassigned user should never be able to initiate the connection from the Studio or through our extension.

**Closed by SiddhanthUnnithan** 2021-08-04 17:39 UTC
