### ISSUE TITLE
Install/Upgrade Azure ML Extension runtime dependencies does not complete

### ISSUE THREAD

**Issue by samuel100** [Microsoft/vscode-tools-for-ai#120] opened 2018-12-21 17:36 UTC
I have installed AzureML SDK following the docs.microsoft.com site and also the VScode AML extension. However, when I try to submit a job it asks to install some extension dependencies - these never seem to get installed as I receive:

error: Please wait while we install/upgrade the Azure ML extension runtime dependencies

Even after waiting over 30mins.

Setup:
OS: Mac OSX High Sierra
VS Code Version: 1.30.1
AML SDK Version: 1.0.6
AML VS Code extension version: 0.4.0

**Comment by shsuman** [comment] 2018-12-21 18:30
And Please select install button when it prompts you to.

**Comment by samuel100** [comment] 2018-12-21 20:46
Many thanks - I will give that a go. However, I would expect the cadence of Azure ML VS Code extension to be the same as the SDK. Otherwise, others will also hit the same problem when they follow the Azure ML SDK install documentation.

**Comment by greazer** [comment] 2019-01-04 19:54
@samuel100, Did @shsuman's advice work for you?

**Comment by greazer** [comment] 2019-01-04 20:55
Highly likely this is a dupe of #123

**Closed by greazer** 2019-01-04 20:55 UTC
Labels: bug, duplicate

**Comment by lokinfey** [comment] 2019-02-18 10:54
Ubuntu 18.04.2
VS Code 1.31.1
Azure Machine Learning 0.42
has the same error

**Comment by shsuman** [comment] 2019-02-18 20:09
Probably because we don't support 1.0.15, please try to install the sdk on your own, just uninstall the sdk and then try to start the extension, it will automatically install everything which is required

**Comment by jeffhorton** [comment] 2019-03-07 21:29
I had this problem of failure to finish ML extension runtime deps on Ubuntu16.
tried 
- deleting .azureml
- uninstalling/restarting/reinstalling extension.

finally fixed by installing missing python venv

sudo apt-get install python3-venv

now works as expected

**Comment by shsuman** [comment] 2019-03-07 22:17
Hello @jeffhorton  I can understand that  you had some difficulties. We plan to debug the dependency installation process more extensively and future versions will tell you preciseyl what the error is, so that user won't be stuck in dependency installation.

**Comment by rpidanny** [comment] 2019-04-10 10:39
@jeffhorton Thanks, it worked for me too.

**Comment by rodneyjoyce** [comment] 2019-08-16 14:43
> * azureml

Where exactly is the .azureml folder on a windows machine? I have tried uninstalling the extension, python and anaconda but it always shows the message above for hours and never completes.

**Comment by jeffhorton** [comment] 2019-08-16 16:40
@rodneyjoyce  that is where I stuck even on linux, the only fix that worked for me was installing the missing python3-venv before installing the extension.

**Comment by shsuman** [comment] 2019-08-16 18:25
@rodneyjoyce  the .azureml folder is in C:\Users\\<user\>\.azureml. It seems like there is some problem in creating your virtual environments. Can you please try to run this script manually on command prompt 

setlocal
set AML_HOME=%HOMEDRIVE%%HOMEPATH%.azureml

set PYTHONBIN=\<python path\>
set AML_VERSION=1.0.15

call "%PYTHONBIN%" -m virtualenv "%AML_HOME%\envs\amlsdk"
call "%AML_HOME%\envs\amlsdk\scripts\activate.bat"

python -m pip install --upgrade pip
python -m pip install flask
python -m pip install werkzeug
python -m pip install azureml-sdk==%AML_VERSION%
call "%AML_HOME%\envs\amlsdk\scripts\deactivate.bat"

Please set your python path in the script. Also, be advised that we have had a lot of problems with python 3.7.x previously, so I would recommend you use Python 3.6.x

**Comment by rodneyjoyce** [comment] 2019-08-17 05:36
Thanks @shsuman :  When I run the above script I get this error on the 5th line:

PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Rod.azureml'

I definitely do not have the .azureml folder:  C:\Users\<user>.azureml  - what installs this folder?

**Comment by shsuman** [comment] 2019-08-20 18:09
@rodneyjoyce  I think its somehow trying to create C:\Users\<user\>.azureml
but we need to create C:\Users\<user\>\.azureml folder

Can you just change  line 2 in the script to the following:
set AML_HOME=C:\Users\Rod\.azureml

**Comment by rodneyjoyce** [comment] 2019-08-26 01:51
Unfortunately, that did not work, however, the new version of the extension - 0.6.2 solves this issue once and for all. Thanks for the help.
