### ISSUE TITLE
[Triage] Trusted workspace prompt is shown always when connecting to CI

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1280] opened 2021-09-22 17:58 UTC
Trusted workspace prompt is shown on subsequent connections even if the workspace was trusted before. Ideally it should be shown on the first connection only.

**Comment by shsuman** [comment] 2021-09-28 07:20
@sevillal Was this a customer issue ?

**Comment by sevillal** [comment] 2021-09-29 16:33
@shsuman it was reported by support eng, I have added you to the thread and the details are also in the Customer Issues internal one note.

**Comment by shsuman** [comment] 2022-04-04 10:14
Dupe of #1275

**Closed by shsuman** 2022-04-04 10:14 UTC
Labels: Epic
