### ISSUE TITLE
Cannot connect to AzureML Compute Instance when starting the terminal with poetry shell

### ISSUE THREAD

**Issue by philipchung** [microsoft/vscode-tools-for-ai#1789] opened 2022-11-08 05:17 UTC
Does this occur consistently? Yes
Repro steps:
1. Provision compute instance on Azure Machine Learning service under "Compute" tab.
2. Click on "VS Code" under Applications.
3. VS Code on local machine launches and attempts to connect via Azure ML - Remote extension, but fails with the error.

I have been able to use this workflow many times before.  Unclear to me what created this error, but it started today.

Action: Resolver.resolve
Error type: TypeError
Error Message: Cannot read properties of undefined (reading 'remoteListeningOn')

Version: 0.20.0
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.73.0
Language: en

<details>
<summary>**Call Stack**</summary>

```
extension.js:2:1956660
extension.js:2:1882501
S._withProgress extensionHostProcess.js:92:44756
S.withProgress extensionHostProcess.js:92:44512
Object.withProgress extensionHostProcess.js:113:44361
n.withProgress extension.js:2:1882119
n.withProgressMessage extension.js:2:1882442
extension.js:2:1956513
```

</details>

<details>
<summary>**Output of Azure ML - Remote Extension in VS Code** </summary>

[Info - 2022-11-08 05:10:05.664] Remote target: {
    "displayName": "chungph-t4x1-gpu1",
    "jupyterUrl": "https://chungph-t4x1-gpu1.westus2.instances.azureml.ms/",
    "websocketUrlTemplate": "chungph-t4x1-gpu1-<WS_PORT>.westus2.instances.azureml.ms/ws",
    "websocketPort": "0",
    "targetType": "Compute instance"
}
[Info - 2022-11-08 05:10:05.673] Remote session: {
    "telemetryTrackingId": "791c57b5-afa8-42e6-8ad9-ccea14e0b467",
    "sessionId": "Pw/jW",
    "expiresOn": 1667884323461
}
[Info - 2022-11-08 05:10:05.673] Telemetry tracker: {
    "sessionId": "Pw/jW",
    "telemetryTrackingId": "791c57b5-afa8-42e6-8ad9-ccea14e0b467"
}
[Error - 2022-11-08 05:10:07.534] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'ui' -> object with constructor 't.AzExtUserInput'
    --- property '_context' closes the circle
	at JSON.stringify (<anonymous>)
	at /Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907677
	at Array.map (<anonymous>)
	at t.Logger.format (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907630)
	at t.Logger.trace (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907529)
	at o.value (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1908919)
	at /Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1956059
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5) []
[Error - 2022-11-08 05:10:07.535] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'ui' -> object with constructor 't.AzExtUserInput'
    --- property '_context' closes the circle
	at JSON.stringify (<anonymous>)
	at /Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907677
	at Array.map (<anonymous>)
	at t.Logger.format (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907630)
	at t.Logger.trace (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907529)
	at o.value (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1908919)
	at C.setupRemoteDependencies (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1959752)
	at o.value (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1908960)
	at /Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1956059
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5) []
[Info - 2022-11-08 05:10:07.537] Using commit id "8fa188b2b301d36553cbc9ce1b0a146ccb93351f" and quality "stable" for server
[Error - 2022-11-08 05:12:11.191] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'ui' -> object with constructor 't.AzExtUserInput'
    --- property '_context' closes the circle
	at JSON.stringify (<anonymous>)
	at /Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907677
	at Array.map (<anonymous>)
	at t.Logger.format (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907630)
	at t.Logger.trace (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907529)
	at o.value (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1908919)
	at /Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1957402 []
[Error - 2022-11-08 05:12:11.194] Error: The terminal process did not finish within 120 seconds. Aborting to exit.
[Info - 2022-11-08 05:12:11.254] Remote target: {
    "displayName": "chungph-t4x1-gpu1",
    "jupyterUrl": "https://chungph-t4x1-gpu1.westus2.instances.azureml.ms/",
    "websocketUrlTemplate": "chungph-t4x1-gpu1-<WS_PORT>.westus2.instances.azureml.ms/ws",
    "websocketPort": "0",
    "targetType": "Compute instance"
}
[Info - 2022-11-08 05:12:11.254] Remote session: {
    "telemetryTrackingId": "791c57b5-afa8-42e6-8ad9-ccea14e0b467",
    "sessionId": "Pw/jW",
    "expiresOn": 1667884323461
}
[Info - 2022-11-08 05:12:11.254] Telemetry tracker: {
    "sessionId": "Pw/jW",
    "telemetryTrackingId": "791c57b5-afa8-42e6-8ad9-ccea14e0b467"
}
[Error - 2022-11-08 05:12:11.677] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'ui' -> object with constructor 't.AzExtUserInput'
    --- property '_context' closes the circle
	at JSON.stringify (<anonymous>)
	at /Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907677
	at Array.map (<anonymous>)
	at t.Logger.format (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907630)
	at t.Logger.trace (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907529)
	at o.value (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1908919)
	at /Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1956457
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5) []
[Error - 2022-11-08 05:12:11.681] Error: Cannot read properties of undefined (reading 'remoteListeningOn')
[Info - 2022-11-08 05:12:11.684] Remote target: {
    "displayName": "chungph-t4x1-gpu1",
    "jupyterUrl": "https://chungph-t4x1-gpu1.westus2.instances.azureml.ms/",
    "websocketUrlTemplate": "chungph-t4x1-gpu1-<WS_PORT>.westus2.instances.azureml.ms/ws",
    "websocketPort": "0",
    "targetType": "Compute instance"
}
[Info - 2022-11-08 05:12:11.684] Remote session: {
    "telemetryTrackingId": "791c57b5-afa8-42e6-8ad9-ccea14e0b467",
    "sessionId": "Pw/jW",
    "expiresOn": 1667884323461
}
[Info - 2022-11-08 05:12:11.684] Telemetry tracker: {
    "sessionId": "Pw/jW",
    "telemetryTrackingId": "791c57b5-afa8-42e6-8ad9-ccea14e0b467"
}
[Error - 2022-11-08 05:12:12.032] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'ui' -> object with constructor 't.AzExtUserInput'
    --- property '_context' closes the circle
	at JSON.stringify (<anonymous>)
	at /Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907677
	at Array.map (<anonymous>)
	at t.Logger.format (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907630)
	at t.Logger.trace (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907529)
	at o.value (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1908919)
	at /Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1956457
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5) []
[Error - 2022-11-08 05:12:12.032] Error: Cannot read properties of undefined (reading 'remoteListeningOn')
[Info - 2022-11-08 05:12:12.037] Remote target: {
    "displayName": "chungph-t4x1-gpu1",
    "jupyterUrl": "https://chungph-t4x1-gpu1.westus2.instances.azureml.ms/",
    "websocketUrlTemplate": "chungph-t4x1-gpu1-<WS_PORT>.westus2.instances.azureml.ms/ws",
    "websocketPort": "0",
    "targetType": "Compute instance"
}
[Info - 2022-11-08 05:12:12.037] Remote session: {
    "telemetryTrackingId": "791c57b5-afa8-42e6-8ad9-ccea14e0b467",
    "sessionId": "Pw/jW",
    "expiresOn": 1667884323461
}
[Info - 2022-11-08 05:12:12.037] Telemetry tracker: {
    "sessionId": "Pw/jW",
    "telemetryTrackingId": "791c57b5-afa8-42e6-8ad9-ccea14e0b467"
}
[Error - 2022-11-08 05:12:12.697] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'ui' -> object with constructor 't.AzExtUserInput'
    --- property '_context' closes the circle
	at JSON.stringify (<anonymous>)
	at /Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907677
	at Array.map (<anonymous>)
	at t.Logger.format (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907630)
	at t.Logger.trace (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907529)
	at o.value (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1908919)
	at /Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1956457
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5) []
[Error - 2022-11-08 05:12:12.698] Error: Cannot read properties of undefined (reading 'remoteListeningOn')
[Info - 2022-11-08 05:12:12.715] Remote target: {
    "displayName": "chungph-t4x1-gpu1",
    "jupyterUrl": "https://chungph-t4x1-gpu1.westus2.instances.azureml.ms/",
    "websocketUrlTemplate": "chungph-t4x1-gpu1-<WS_PORT>.westus2.instances.azureml.ms/ws",
    "websocketPort": "0",
    "targetType": "Compute instance"
}
[Info - 2022-11-08 05:12:12.715] Remote session: {
    "telemetryTrackingId": "791c57b5-afa8-42e6-8ad9-ccea14e0b467",
    "sessionId": "Pw/jW",
    "expiresOn": 1667884323461
}
[Info - 2022-11-08 05:12:12.715] Telemetry tracker: {
    "sessionId": "Pw/jW",
    "telemetryTrackingId": "791c57b5-afa8-42e6-8ad9-ccea14e0b467"
}
[Error - 2022-11-08 05:12:13.035] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'ui' -> object with constructor 't.AzExtUserInput'
    --- property '_context' closes the circle
	at JSON.stringify (<anonymous>)
	at /Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907677
	at Array.map (<anonymous>)
	at t.Logger.format (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907630)
	at t.Logger.trace (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1907529)
	at o.value (/Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1908919)
	at /Users/chungph/.vscode/extensions/ms-toolsai.vscode-ai-remote-0.20.0/dist/src/extension.js:2:1956457
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5) []
[Error - 2022-11-08 05:12:13.035] Error: Cannot read properties of undefined (reading 'remoteListeningOn')

</details>

**Comment by sevillal** [comment] 2022-11-08 20:41
Thanks for filing this issue @philipchung! We are really sorry to hear that you are having troubles with the connection.

I have checked the error message you see and it should be unrelated, although we will fix it to avoid any confusion, I have created [this issue](https://github.com/microsoft/vscode-tools-for-ai/issues/1792) to track.

Regarding your connection issue I have some questions:
1. Once you are unable to connect could you please try running command "Azure ML: Kill Azure ML websocket server on compute instance" and retry connecting. Does is help?
2. If previous step does not help, could you try restarting the compute instance and reconnect?

I am wondering if you are open to have a quick triage meeting to check the issue live, if so please reach out to me at sevillal@microsoft.com.

**Comment by shsuman** [comment] 2022-11-18 09:53
Closing because of inactivity. Please reopen if need be :)

**Comment by philipchung** [comment] 2022-11-18 17:41
Hi, this issue is not resolved yet for me.  I had a chat with @sevillal who said he would discuss with the product team.  I separately have met with AzureML support engineer who said may be a bug and will reach out to @sevillal.

**Comment by philipchung** [comment] 2022-11-18 17:43
@shsuman, I don't have the privileges on this repo to reopen.  Can you please re-open this issue until it has been properly resolved?

**Comment by sevillal** [comment] 2022-11-18 19:00
@philipchung I have reopen the issue, I will be in touch with you later today.

**Comment by philipchung** [comment] 2022-11-18 22:16
I may have isolated the problem.

After compute instance creation, I run a configuration script to use poetry as a python environment manager, and then add a script to ~/.bashrc to automatically enter the poetry virtual environment (`poetry shell`).

When I remove the step to automatically enter the virtual environment in ~/.bashrc, then I have no issue connecting to the compute instance.  It seems that installing VSCode remote server is dependent on the default conda environment that is used.  It would be nice if this was not the case.

Here is a minimal reproduction of the configuration script (substitute USERNAME and PROJECT_NAME)
```sh
#!/usr/bin/env bash

### --- Deactivate Conda --- ###
# Deactivate default conda environments so we don't use a version of python managed by conda.
eval "$(conda shell.bash hook)"
for i in $(seq ${CONDA_SHLVL}); do
    conda deactivate
done

# Environment Variables (substitute your azure username and repo/folder name)
export USERNAME=""
export PROJECT_NAME=""
export CLOUDFILES_HOME="/home/azureuser/cloudfiles/code/Users/${USERNAME}"
export PROJECT_PATH="${CLOUDFILES_HOME}/${PROJECT_NAME}"


### --- Poetry --- ###
curl -sSL https://install.python-poetry.org | /usr/bin/python3 -
export PATH="/home/azureuser/.local/bin:$PATH"
cd ${PROJECT_PATH}
# Assumes that $PROJECT_PATH is a directory that contains a pyproject.toml file or poetry.lock file that specifies the environment.
poetry install

# Configure .bashrc to go to project directory and enter poetry shell on terminal launch
echo '
export PATH="/home/azureuser/.local/bin:$PATH"
export USERNAME='"${USERNAME}"'
export PROJECT_NAME='"${PROJECT_NAME}"'
export CLOUDFILES_HOME='"${CLOUDFILES_HOME}"'
export PROJECT_PATH='"${PROJECT_PATH}"'
cd ${PROJECT_PATH}
poetry shell  # <-- this is the line that causes a problem
' >> ~/.bashrc
```

**Comment by sevillal** [comment] 2022-11-19 00:28
@philipchung thanks for those details, I will try to repro with the script.

**Comment by sevillal** [comment] 2022-11-22 00:03
@philipchung I was able to repro the issue, it seems that the `poetry shell` command is interfering with our installation script. I need to spend some time to investigate the root cause. In the meantime I want to confirm that you can unblock your self by removing that line from your script and manually running it after you connect.

**Comment by philipchung** [comment] 2022-11-22 00:04
Yes, I am unblocked.  Thank you for your help.

**Comment by shsuman** [comment] 2022-11-28 16:54
@philipchung @sevillal Apologies for wrongly closing this issue. I was not aware of your offline discussions :(

**Comment by sevillal** [comment] 2024-08-23 16:20
Closing this as we haven't heard of other customers facing this issue. Please reopen if needed.

**Closed by sevillal** 2024-08-23 16:20 UTC
Labels: customer-issue, area-remote-desktop
