### ISSUE TITLE
PD-L1

### ISSUE THREAD

**Issue by mutant0204** [microsoft/vscode-tools-for-ai#1571] opened 2022-05-12 03:42 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSessionsChanged
Error type: 123
Error Message: Unknown Error retrieving susbcriptions from Azure Account extension

Version: 0.10.0
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.67.1
Language: ko

<details>
<summary>Call Stack</summary>

```
_.<anonymous> extension.js:2:2324475
s extension.js:2:2321343
```

</details>

**Comment by SiddhanthUnnithan** [comment] 2022-05-12 17:29
Thank you for filing this @mutant0204. Do you mind elaborating on what steps it took to get to the error that you're seeing? What are you attempting to do in the extension?

**Comment by sevillal** [comment] 2022-05-13 17:17
Potential duplicate of https://github.com/microsoft/vscode-tools-for-ai/issues/1569

**Comment by shsuman** [comment] 2022-08-11 08:51
Tracking it in #1634. Please refer to that issue for updates :)

**Closed by shsuman** 2022-08-11 08:51 UTC
Labels: customer issue

**Comment by shsuman** [comment] 2022-08-11 08:59
Closing because of inactivity. Please reopen if need be :)
