### ISSUE TITLE
Unable to install  Azure Machine Learning - Remote 

### ISSUE THREAD

**Issue by Nguenda** [microsoft/vscode-tools-for-ai#2071] opened 2023-06-06 07:20 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureml.viewContext.computeInstance.connectInNewWindow
Error type: 412
Error Message: Unable to install Azure Machine Learning - Remote extension, please retry installing from VS Code Extensions view. Operation timed out.

Version: 0.32.2
OS: linux
OS Release: 5.15.0-1035-azure
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.js:2:2359477
```

</details>

**Comment by shsuman** [comment] 2023-06-07 06:51
Closing as duplicate of #2070

**Closed by shsuman** 2023-06-07 06:51 UTC
Labels: customer-issue
