### ISSUE TITLE
Datastore Integration into AML 

### ISSUE THREAD

**Issue by akashraju4** [microsoft/vscode-tools-for-ai#271] opened 2019-07-24 05:35 UTC
Submitting an experiment into AML through the AML Extension has a 300 MB limit. 

![image](https://user-images.githubusercontent.com/28133688/61767755-1c20ef00-ad9a-11e9-94cf-6aedcdc649c4.png)

**Comment by greazer** [comment] 2019-07-31 21:35
Dupe of #255

**Closed** 2019-07-31 21:35 UTC
