### ISSUE TITLE
Loss connection with Azure ML

### ISSUE THREAD

**Issue by smalltt** [microsoft/vscode-tools-for-ai#2055] opened 2023-05-26 19:14 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: Resolver.resolve
Error type: 182
Error Message: Internal extension error: redacted:key parameters cannot be read from extension context. Please try again

Version: 0.30.0
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
n.initializeTokenAcquisitionParams extension.js:2:1930557
async n.acquireTokenWithExpiration extension.js:2:1928206
async n.acquireBearerToken extension.js:2:1927615
```

</details>

**Comment by shsuman** [comment] 2023-06-07 10:58
@smalltt We are aware of this issue and currently following up with VSCode here https://github.com/microsoft/vscode/issues/184490

However, this is a transient issue if you just retry, it would get resolved.

I am closing this for now. Please let me know if the issue is persistent for you or you are blocked

**Closed** 2023-06-07 10:59 UTC
Labels: customer-issue
