### ISSUE TITLE
Can not connect to visual studio code desktop from AML

### ISSUE THREAD

**Issue by edab-code** [microsoft/vscode-tools-for-ai#2178] opened 2023-09-20 16:02 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: UriHandler.handleUri
Error type: 344
Error Message: Error obtaining refresh redacted:key your subscription. Please try again

Version: 0.37.2023092009
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.82.2
Language: en

<details>
<summary>Call Stack</summary>

```
j.<anonymous> extension.js:2:2525853
s extension.js:2:2521931
```

</details>

**Comment by shsuman** [comment] 2023-09-21 06:23
Duplicate of #2177

**Closed by shsuman** 2023-09-21 06:23 UTC
Labels: triage-needed
