### ISSUE TITLE
[Timebox] Investigate why the YAML language server was causing the extension to fail when activating

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#873] opened 2021-01-06 18:38 UTC

**Comment by sevillal** [comment] 2021-01-13 02:42
Closing since root cause has been found. Issue summary:

- Yaml language server initialization fails due to bug when getting schema association from other extensions yamlValidation contributions
- How to repro? Install Docs Authoring Pack extension and reload the window

**Closed by sevillal** 2021-01-13 02:42 UTC
Labels: Epic
