### ISSUE TITLE
Azure ML plugin

### ISSUE THREAD

**Issue by MrBenjaminLeb** [microsoft/vscode-tools-for-ai#1574] opened 2022-05-13 12:58 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSubscriptionsChanged
Error type: 123
Error Message: Unknown Error retrieving susbcriptions from Azure Account extension

Version: 0.8.2
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.66.1
Language: en

<details>
<summary>Call Stack</summary>

```
b.<anonymous> extension.js:2:1989015
s extension.js:2:1985916
```

</details>

**Comment by sevillal** [comment] 2022-05-13 17:22
Potential duplicate of https://github.com/microsoft/vscode-tools-for-ai/issues/1569

**Comment by sevillal** [comment] 2022-05-13 17:23
@MrBenjaminLeb could you please try updating to the latest version of the Azure ML extension?

**Comment by shsuman** [comment] 2022-06-07 10:24
Closing because of inactivity. Please reopen if need be

**Closed by shsuman** 2022-06-07 10:24 UTC
Labels: customer issue
