### ISSUE TITLE
continuously asks for sign-in

### ISSUE THREAD

**Issue by DeltaCharlieAlpha** [microsoft/vscode-tools-for-ai#1602] opened 2022-06-29 15:25 UTC
Does this occur consistently?  YES
Repro steps:

1. Open VSCode
2. Open Azure Extension
3. Expand Machine Learning Tab
4. Sign in prompt appears - "The Azure Machine Learning extension needs you to sign into Azure.  Please sign in to use Azure ML Extension."
5. Click "Sign In"
6. Select proper account from "Pick an Account" window to sign into account
7. Notice: "You are signed in now and can close this window"
8. Right Click on compute target under Machine Learning tab
9. select Connect
10. Notice, error message appears (see details below) "Unknown Error retrieving subscriptions from Azure Account extension"
11. Notice - new Sign-in pop up appears.
12. Clicking Sign In on new sign in dialog repeats steps 10,11, and 12 infinitely.  Clicking cancel dismisses, and extension seems connected to compute.

Action: azureAccount.onSessionsChanged
Error type: 123
Error Message: Unknown Error retrieving susbcriptions from Azure Account extension.  

Version: 0.12.0
OS: linux
OS Release: 5.4.0-1056-azure
Product: Visual Studio Code
Product Version: 1.68.1
Language: en

<details>
<summary>Call Stack</summary>

```
_.<anonymous> extension.js:2:2329781
s extension.js:2:2326649
```

</details>

**Comment by shsuman** [comment] 2022-07-01 10:25
Looks related to https://github.com/microsoft/vscode-azureml/issues/122.

@tbombach Can you please take a look ?

**Comment by shsuman** [comment] 2022-09-22 08:34
@DeltaCharlieAlpha We have shipped a fix for this issue. Can you please upgrade the extension to 0.18.0 and let us know if its fixed for you?

**Comment by DeltaCharlieAlpha** [comment] 2022-09-23 17:11
This seems to have gotten worse.  Before when I got in the loop, I could authenticate a few times and then cancel.  Now I still get the loop but if I cancel, I can't access my remote compute.

**Comment by tbombach** [comment] 2022-09-23 21:03
@DeltaCharlieAlpha I'm sorry you're running into this issue. Thank you for listing the steps that you took when you encountered the problem - I'll try this steps and see if I can reproduce the same behavior.

**Comment by shsuman** [comment] 2024-08-16 06:13
@DeltaCharlieAlpha Are you still facing this issue ?

**Comment by shsuman** [comment] 2024-08-22 07:16
Closing because of inactivity. Please reopen if need be :)

**Closed by shsuman** 2024-08-22 07:16 UTC
Labels: customer-issue, area-sign-in, iteration-candidate, t-unknown-sub-error
