### ISSUE TITLE
Default to creating a temporary one-off environment when a user makes dependency changes to a curated environment definition.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#562] opened 2020-05-03 03:32 UTC
We should default to creating a one-off environment when the user makes a dependency change to a curated environment.

The environment usage will fail if a user passes an environment definition with a curated environment and a different set of dependencies.

**Comment by tbombach** [comment] 2020-05-06 21:07
We believe this is done already - assigning to @sevillal to confirm

**Comment by sevillal** [comment] 2020-05-07 18:31
Unable to reproduce the issue and it looks like we are doing the correct handling. Closing it by now.

@SiddhanthUnnithan has started a thread with the user who reported this, we can reopen in case we are able to reproduce after user's input.

**Closed by sevillal** 2020-05-07 18:31 UTC
