### ISSUE TITLE
On VSCode Startup: "Initialize log file failed: Path must be a string. Received undefined." Source: Visual Studio Code Tools for AI (Extension)

### ISSUE THREAD

**Issue by BStudent** [Microsoft/vscode-tools-for-ai#50] opened 2018-08-30 06:54 UTC
Latest VSCode TfAI installed / running locally on RHEL Server release 7.5 (Maipo)
When I start VSCode I get this message box in the lower-right-hand corner of the screen:
(represented below as ascii art where `(x)` and `*`, `v`, and `x` represent buttons/icons).
```
+-----------------------------------------------------------------------------------------+
| (x)  Initialize log file failed: Path must be a string. Received undefined.     *  v  x |   
|                                                                                         |
|Source: Visual Studio Code Tools for AI (Extension)                                      |
+-----------------------------------------------------------------------------------------+
```

**Comment by linmajia** [comment] 2018-08-30 07:54
@BStudent , thank you very much for the feedback.

VS Code Tools for AI does not officially support Linux yet, so there may be potential bugs. The root cause of this issue is that the logger is not initialized correctly on Linux. We will fix the problem soon and welcome to tell us any issues you find on Linux.

Thanks.

**Comment by linmajia** [comment] 2018-08-30 07:55
Duplicate of https://github.com/Microsoft/vscode-tools-for-ai/issues/44

**Closed** 2018-08-30 07:56 UTC
Labels: bug

**Comment by AceHack** [comment] 2018-11-12 19:46
I am having same issue, when will it be fixed?

**Comment by AceHack** [comment] 2018-11-12 22:35
Yes, please don't allow me to install an extension on an OS that does not work for the extension.  This is silly.
