### ISSUE TITLE
Failed hanging on 'code'

### ISSUE THREAD

**Issue by jlbradley1844** [microsoft/vscode-tools-for-ai#2052] opened 2023-05-24 21:27 UTC
Does this occur consistently? 
Repro steps:

Not a blocking issue, just opening this as suggested in the VSCode promts when I get the error.
1. Open VSCode with Azure extensions
2. Click on workspaces pane, where it shows "open folder or workspace"
3. In the resulting dialog, select  /home/azureuser/cloudfiles
4. Open workspace in the 'cloudstore' shared folder from azure

This hangs the Azure extensions. I have to use "Close remote connection" to fix.

Subsequent connections under VSCode allow me to select default subscription and workspace. As such, no need to do above, since my workspace appears in the "Machine Learning" pane.

Action: Resolver.resolve
Error type: 182
Error Message: Internal extension error: redacted:key parameters cannot be read from extension context. Please try again

Version: 0.30.0
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
n.initializeTokenAcquisitionParams extension.js:2:1930557
async n.acquireTokenWithExpiration extension.js:2:1928206
async n.acquireBearerToken extension.js:2:1927615
```

</details>

**Comment by shsuman** [comment] 2023-06-07 10:59
@jlbradley1844  We are aware of this issue and currently following up with VSCode here https://github.com/microsoft/vscode/issues/184490

However, this is a transient issue and if you just retry, it would get resolved.

I am closing this for now. Please let me know if the issue is persistent for you or you are blocked

**Closed** 2023-06-07 11:00 UTC
Labels: customer-issue
