### ISSUE TITLE
[DRI-Lite] All items for the week of 10/11

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1301] opened 2021-10-14 15:56 UTC

**Comment by shsuman** [comment] 2021-10-19 07:33
Summary Report
 
Week: Oct 11th, 2021
 
# of New Issues: 3
 
Issues Triaged:
1.	[Triage] Plot is not rendering in VSCode while connecting to AML Compute
2.	[Triage] Frequent Disconnection from Azure ML Compute while working
3.	[Triage] Ports to open to allow connection to CI with VS Code remote server

Issues Closed:
1.	[Triage] Connection to VS Code stopped working for a customer
a.	Customer reported connection is working fine now.
2.	[Triage] Frequent Disconnection from Azure ML Compute while working
a.	We have a fix for 401 errors in connection, I have shared a custom Vsix with the customer for him to try it out.
 
Open Items:
1.	[Triage] Plot is not rendering in VSCode while connecting to AML Compute
a.	This seems to be a limitation on remote connections, need more investigation. In the meanwhile we have provide some workarounds.
2.	[Triage] Remote VS code certificate trust issue
a.	Waiting for customer to try “http.systemCertificates” setting.
3.	Long running task - lost Azure Account connection
a.	We need to identify who was the customer facing this issue and update the OneNote. 
4.	[Triage] Ports to open to allow connection to CI with VS Code remote server
a.	Need more info from the customer. Follow email thread.
5.	Trusted workspace prompt is shown always when connecting to CI
a.	Possible solutions listed in the problem issue.
6.	VS Code is stuck installing server when connecting to CI (jupyer, jupyterlab and terminal stuck)
a.	Jupyter server hangs after installing vscode server.
b.	Created some issues that might help mitigate.
c.	New test: 
i.	Minifying the bash script seems to help.
ii.	1000 times executing installation script:
1.	Unminified: Fails after ~5 retries
2.	Minified: Works fine all the 1000 times
7.	VS Code cannot connect to compute instance in Azure Machine Learning
a.	Will be solved as part of item 6.
8.	Reconnection after remote session has been open for a while
a.	Will be solved with Reconnection Mitigation fixes.
9.	Don't attempt starting a compute instance after it has already been started.
a.	PR ready. Should be fixed in next release.
10.	Connection error - frequently getting disconnected
a.	Will be solved with Reconnection Mitigation fixes.

**Closed** 2021-10-19 07:33 UTC
Labels: Epic
